spring.application.name=journalApp
server.port=8080
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journalAppDB
# spring.data.mngodb.username=yourUsername
# spring.data.mongodb.password=yourPassword

#indexing
spring.data.mongodb.auto-index-creation=true